### ISSUE TITLE
this needs to be migrated to the new way of triggering

### ISSUE THREAD

**Issue by goern** [thoth-station/init-job#146]
;)

**Comment by harshad16** [comment]
Was working on that ;)

**Comment by fridex** [comment]
What is this issue about? Is it still relevant?

**Comment by harshad16** [comment]
The deployment of init-job needs a different module and manually monitoring while deploying. so that why we are migrating the triggering method, it would be updated in thoth-ops. A simple ansible playbook in thoth-ops which deploys init-job in test and stage respectively with their required templates and images.

I will document and add an ansible playbook in a day or so.

**Comment by fridex** [comment]
A fresh deployment needs to have indexes registered and scheduled analysis of "core" packages. So init-job needs to be triggered on a green-field deployment.

If we want to monitor "new" indexes on our AICoE index, why not just create a cronjob, which will periodically crawl our AICoE index and insert relevant entries. All the monitoring/alerting stuff we have is then reused (it just monitors another cronjob in deployment). There is already an option for that - `--register-indexes-only`.

**Comment by goern** [comment]
is this still valid?

**Comment by fridex** [comment]
This feels like a good-first-issue. There is a need to create a cronjob that would run the logic implemented in init-job with different parameters than the "init-job" job. So we automatically register Python indexes we (Thoth inhabitants) provide.

As we build manylinux compliant packages and thus have one Python index, I would consider this low priority.

**Comment by goern** [comment]
ping

**Comment by fridex** [comment]
+1, sounds good to me :+1:
